### ISSUE TITLE
need some fixes

### ISSUE THREAD

**Issue by SydOps** [retr0h/ansible-logrotate#12]
This ansible role makes the task easier to define different logrotate configuration for different applications. The idea to make it run as ansible module is better than the other hottest ansible logrotate galaxy role (https://github.com/nickhammond/ansible-logrotate) 

But when I implement the vars file, I got two problems, in fact three. Here is my task file.
```
$ cat roles/common/tasks/logrotate.yml
- name: Define logrotate config
  logrotate: name=syslog path='/var/log/cron /var/log/maillog /var/log/messages /var/log/secure /var/log/spooler'
  args:
    options:
      - compress
      - copytruncate
      - missingok
      - sharedscripts
      - weekly
      - rotate 12
      - postrotate
      - '  /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
      - endscript
  tags:
    - logrotate
```

So I have to:

### put path into one line: `path='/var/log/cron /var/log/maillog /var/log/messages /var/log/secure /var/log/spooler'`

can we have something as:
```
- name: Define logrotate config
  logrotate: name=syslog 
  path:
     - /var/log/cron 
     - /var/log/maillog 
     - /var/log/messages 
     - /var/log/secure 
     - /var/log/spooler
  args:
    ...
```

### put spaces before `exec script`.

      - '  /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'

###  the `{` is in new line, as below.
```
/var/log/cron /var/log/maillog /var/log/messages /var/log/secure /var/log/spooler
{
  compress
  copytruncate
  missingok
  sharedscripts
  weekly
  rotate 12
  postrotate
    /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
  endscript
}
```
I know it should work, but will be better to update as
```
/var/log/cron /var/log/maillog /var/log/messages /var/log/secure /var/log/spooler {
  ...
}
```

**Comment by retr0h** [comment]
> - name: Define logrotate config
>   logrotate: name=syslog 
>   path:
>      - /var/log/cron 
>      - /var/log/maillog 
>      - /var/log/messages 
>      - /var/log/secure 
>      - /var/log/spooler'
>   args:
>     ...

Hey @SydOps, I implemented more or less what you wanted in #15 around passing a list to path.  As to the syntax of the logrotate conf files, they are rendered on new lines.  I'm also not inclined to change the placement of the brackets.  However, the functionality you requested is now implemented.

```
/var/log/log1.log
/var/log/log2.log
{
  daily
  missingok
  rotate 8
  compress
  delaycompress
  copytruncate
  notifempty
}
```

**Comment by SydOps** [comment]
Thanks @retr0h 

I think the format is wrong. Can we still have all path on the same line?

```
$ cat /etc/logrotate.d/syslog
/var/log/cron
/var/log/maillog
/var/log/messages
/var/log/secure
/var/log/spooler
{
  compress
  copytruncate
  missingok
  sharedscripts
  weekly
  rotate 12
  postrotate
    /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
  endscript
}
```

**Comment by SydOps** [comment]
Here is the final syslog logrotate I want to have:
```
/var/log/cron /var/log/maillog /var/log/messages /var/log/secure /var/log/spooler {
  compress
  copytruncate
  missingok
  sharedscripts
  weekly
  rotate 12
  postrotate
    /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
  endscript
}
```

**Comment by SydOps** [comment]
See the sample of http://www.linuxcommand.org/man_pages/logrotate8.html with two logs :

```

       "/var/log/httpd/access.log" /var/log/httpd/error.log {
           rotate 5
           mail www@my.org
           size=100k
           sharedscripts
           postrotate
                                     /sbin/killall -HUP httpd
           endscript
       }
```

**Comment by retr0h** [comment]
> I think the format is wrong. Can we still have all path on the same line?

Sure, I guess I don't care all that much.  Implemented in #16.

**Comment by SydOps** [comment]
Perfect. I got all I need. 👍 

We should release it now, create a release on it: `v1.0`

**Comment by retr0h** [comment]
> We should release it now, create a release on it: v1.0

done

**Comment by SydOps** [comment]
My final task yaml file for reference:
```
- name: Define logrotate config
  logrotate:
    name: syslog
    path:
       - /var/log/cron
       - /var/log/maillog
       - /var/log/messages
       - /var/log/secure
       - /var/log/spooler
  args:
    options:
      - compress
      - copytruncate
      - missingok
      - sharedscripts
      - weekly
      - rotate 12
      - postrotate
      - '  /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true'
      - endscript
  tags:
    - logrotate
```
